# Generated by Django 4.2.4 on 2024-03-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="phone_number",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="center",
            name="website",
            field=models.CharField(default="", max_length=200),
        ),
    ]
