# Generated by Django 4.2.4 on 2024-03-15 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientApplicationContext",
            fields=[
                (
                    "patient_application_context_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "has_had_suicidal_thoughts_in_last_90_days",
                    models.BooleanField(default=False),
                ),
                ("has_used_drugs_in_last_90_days", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
