# Generated by Django 4.2.4 on 2024-03-16 17:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_patientapplicationcontext"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="address",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="patient",
            name="has_disability",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="health_insurance",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="patient",
            name="health_insurance_identifier",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_open_to_faith_based_treatment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="mental_health_diagnoses",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="sex",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="patient",
            name="using_medication_assisted_therapies",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="using_substances",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), default=list, size=None
            ),
        ),
    ]
