# Generated by Django 4.2.4 on 2024-03-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_provider_user_is_provider_patient_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="placement_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("applied", "Applied"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("in_treatment", "In treatment"),
                    ("completed_treatment", "Completed treatment"),
                ],
                default="pending",
                max_length=200,
            ),
        ),
    ]
