# Generated by Django 4.2.4 on 2024-03-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_patient_placement_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="center",
            name="image",
            field=models.FileField(blank=True, upload_to="centers/images/"),
        ),
    ]
