# Generated by Django 4.2.4 on 2024-04-25 18:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_center_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="can_travel",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="criminal_history",
            field=models.CharField(default="", max_length=10000),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_held_in_confinement",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="miles_can_travel",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="weeks_held_in_confinement",
            field=models.IntegerField(default=0),
        ),
    ]
