# Generated by Django 4.2.4 on 2024-04-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_patient_can_travel_patient_criminal_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="available_beds",
            field=models.IntegerField(default=0),
        ),
    ]
