# Generated by Django 4.2.4 on 2024-04-29 16:13

import core.models.center
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_center_available_beds"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="accepts_patients_on_methadone",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="center",
            name="accepts_patients_who_are_pregnant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="center",
            name="accepts_patients_who_are_uninsured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="center",
            name="accepts_patients_with_co_occuring_disorders",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="center",
            name="accepts_patients_with_disabilities",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="center",
            name="center_type",
            field=models.CharField(
                choices=[
                    ("detox", "Detox"),
                    (
                        "clinical stabilization services",
                        "Clinical Stabilization Services",
                    ),
                    ("transitional support services", "Transitional Support Services"),
                    ("residential rehabilitation", "Residential Rehabilitation"),
                    ("outpatient rehab", "Outpatient Rehab"),
                    ("multiple outpatient", "Multiple Outpatient"),
                    ("dual diagnosis", "Dual Diagnosis"),
                    ("BOAT", "Boat"),
                    ("PHP", "Php"),
                ],
                default="residential rehabilitation",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="center",
            name="eligible_sexes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("male", "Male"),
                        ("female", "Female"),
                        ("other", "Other"),
                    ],
                    max_length=200,
                ),
                default=core.models.center.get_eligible_sex_default,
                size=None,
            ),
        ),
    ]
