# Generated by Django 4.2.4 on 2024-04-29 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_center_accepts_patients_on_methadone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="center",
            name="is_disability_compatible",
        ),
    ]
